# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistica_l01_development  
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      DEV_USER_DB: postgres
      DEV_PASS_DB: postgres
      DEV_HOST_DB: db                # ← host = nombre del servicio
    volumes:
      - .:/rails:cached
      - bundle_cache:/usr/local/bundle
    command: bash -lc "bundle install && rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3001"
    depends_on:
      - db

volumes:
  bundle_cache:
  db_data:
